### ISSUE TITLE
Actually crack it

### ISSUE THREAD

**Issue by ccrpr** [P-DennyGamingYT/Synapse-Beta#4]
I tried launching the software but it seems I cannot execute anything without a Synapse V3 account. The only thing this did is hide the loading screen for the Hollywood code editor that is planned to be open-sourced at release since 2020. It's just a visual thing, it's not actually cracked. Can you fix this and really crack it?

**Comment by P-DennyGamingYT** [comment]
This is isn't an open source build. I recieved this file directly from the v3 server (which I got from an anonyous insider) and then found a bypass inside the UI and I am going to crack and release the source code (if i can). So Im working on a way to basically fully bypass the login instead of just the login page so that I can release a fully working version. If you would like to adress this futher with me please DM me on discord @ [YT]P-Denny#7313
